### ISSUE TITLE
A display bug on Windows11

### ISSUE THREAD

**Issue by Fly143** [popojan/goban#42]
On Windows11, there is a display bug with the chess pieces, and there is a layer of black coating on the surface of the chess pieces.
![QQ截图20240110003552](https://github.com/popojan/goban/assets/80356009/5c302e06-3737-4f4c-ae08-1b2107b563ff)

**Comment by popojan** [comment]
Hi Fly143, seems like an issue with the übershader I cannot reproduce.

1. Have you also upgraded graphics card or its drivers?
2. Could you please confirm it also applies to the "Minimalistic thin" appearence?
3. Might be related to soft-shadows, attached is a zipped `fragment.glsl` shader with shadows turned off, if you were so kind to try it out and tell me whether it removes also the black patches, it would help me debug the problem. The [fragment.zip](https://github.com/popojan/goban/files/14000435/fragment.zip) is to be unzipped to `data/shaders/legacy/`.


Thank you for submitting the bug report.

**Comment by Fly143** [comment]
@popojan I'm very sorry that I forgot I also raised an issue, and I hope my message didn't reply late. There is no display problem with other appearances, only this one has this display problem. After using the fargment.zip file you provided, the problem was solved.
![QQ截图20240317225430](https://github.com/popojan/goban/assets/80356009/cbd53da0-088d-4509-a747-0fc8c87fde74)
![QQ截图20240317225417](https://github.com/popojan/goban/assets/80356009/2176b865-c073-4e43-b473-ec2d69e2644d)
![QQ截图20240317225629](https://github.com/popojan/goban/assets/80356009/84b7d422-e50c-42eb-bf58-c6d4366e01cc)

**Comment by Fly143** [comment]
In addition, do you need Chinese translation? Maybe you can provide a Chinese option for the software?

**Comment by popojan** [comment]
@Fly143 Thank you for trying the modified shader out. Now it is obvious it is the softshadow calculation causing trouble. Good to know the shadows work well with the simplified appearence, I may compare its code even though I cannot replicate the black artifacts myself.

My apology for late reaction to your answer.

As for the Chinese translation, it would be nice, as it seems mostly Chinese people download the binaries.
Most strings are already part of the gui and json configuration files, I will check whether there is anything hard-coded left. 

Thank you for your kind help.

**Comment by Fly143** [comment]
> @Fly143感谢您修改后的着色器。现在很明显是软阴影计算了问题。很高兴知道阴影与简化的外观配合得很好，我可能会比较它的代码，尽管我自己无法复制黑色伪影。
> 
> 很抱歉这么晚才回复您的回答。
> 
> 对于中文翻译，那就更好了，因为好像大多数中国人都下载了二进制文件。 大多数字符串已经是 gui 和 json 配置文件的一部分，我会检查是否还剩下任何编码硬的内容。
> 
> 怀念的帮助。

@popojan Sorry for the belated Chinese translation!

I hope you still have the intention to make a Chinese version.

File→文件

save now →保存棋谱

system→系统

exit→退出

.............................

view→显示方式

appearance→外观

Windows→窗口

fullscreen→全屏

overlay→显示手数

last move→最后一手

camera→视角

reset→复位

animate→播放动画

camera preset→视角预设

save→保存

clear→还原

.............................

game→游戏

Black player→黑棋

human→人类

white player→白棋

board siez→棋盘大小

komi→贴目

handicap→让子棋

even→不让子

2 stones→让2子

3 stones→让3子

............................

move→落子

pass→停一手

（black passes→黑棋停一手）

（white passes→白棋停一手）

kibitz move→提示

undo→悔棋

resign→认输

（white wins by resignation→白中盘胜）

（black wins by resignation→黑中盘胜）

（white wins by 21.5→白胜21.5目）

（black wins by 21.5→黑胜21.5目）

......................

analyze→分析

territory→形势判断

....................

debug→调试

framerate→帧率

abuot→关于我们

version→版本

**Comment by popojan** [comment]
Thank you very much, Fly143.
Yes, I still have the intention to include Chinese translation (and sporadically continue the development). 🙏
